name: clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './dcs_interface ./utilities ./test'
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: '{BasedOnStyle: LLVM, IndentWidth: 4, BreakBeforeBraces: Linux, UseTab: Never, AllowShortBlocksOnASingleLine: Empty, BinPackArguments: false, BinPackParameters: false, ColumnLimit: 120}'
